# Usamos o Nginx para servir nossos arquivos estáticos (HTML/CSS/JS)
FROM nginx:alpine

# Copia os arquivos do PWA para o diretório padrão do Nginx
COPY . /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80